### ISSUE TITLE
Type-asserting to ref type inside composite type shouldn't work.

### ISSUE THREAD

**Issue by tcard** [tcard/sgo#1]
Right know this is forbidden:

```go
v.(*int)
```

But this isn't:
```go
v.([]*int)
```

To fix this, `"github.com/tcard/sgo/sgo/types".assertableTo` needs to walk composite types looking for refs.

**Comment by mvader** [comment]
I will fix this one, if that's okay with you.

Should all these cases be forbidden or just the first one?
```
v.([]*foo)
v.(map[*foo]bar)
v.(map[foo]*bar)
v.(map[*foo]*bar)
```

**Comment by tcard** [comment]
Great!

All "optionable" types (ie. pointers, channels, functions, maps, interfaces) should be forbidden if not wrapped in an optional, recursively. All of these should be forbidden:

```go
v.([]*foo)
v.(map[*foo]bar)
v.(map[*foo]bar)
v.(map[foo]*bar)
v.(map[*foo]*bar)
v.(?map[*foo]*bar)
```

This is allowed:

```go
v.(?map[?*foo]?*bar)
```

**Comment by tcard** [comment]
@mvader Great!

All "optionable" types (ie. pointers, channels, functions, maps, interfaces) should be forbidden if not wrapped in an optional, recursively. All of these should be forbidden:

```go
v.([]*foo)
v.(map[*foo]bar)
v.(map[*foo]bar)
v.(map[foo]*bar)
v.(map[*foo]*bar)
v.(?map[*foo]*bar)
```

This is allowed:

```go
v.(?map[?*foo]?*bar)
```

**Comment by mvader** [comment]
Update:

```
example.sgo:15:13: cases[1] (variable of type interface{}) cannot be type-asserted to map[*int]int (must be wrapped in optional)
example.sgo:16:13: cases[2] (variable of type interface{}) cannot be type-asserted to map[int]*int (must be wrapped in optional)
example.sgo:17:13: cases[3] (variable of type interface{}) cannot be type-asserted to map[*int]*int (must be wrapped in optional)
```

Seems like map is already not allowed.
