### ISSUE TITLE
Consider using directive form for "For SGo:" doc comments.

### ISSUE THREAD

**Issue by shurcooL** [tcard/sgo#20]
In the README, there's a section describing "For SGo:" doc comments.

https://github.com/tcard/sgo#for-sgo-doc-comments

Right now they look like this:

```Go
// For SGo: func(string, func(w http.ResponseWriter, req *http.Request)
func HandleFunc(pattern string, handler func(ResponseWriter, *Request))
```

Which looks a lot like a normal comment written by humans for humans, without following any special syntax and without having special meaning to a compiler or other tool. Someone who's unfamiliar with it may think the above code is no different than:

```Go
// This is for SGo: func(string, func(w http.ResponseWriter, req *http.Request)
func HandleFunc(pattern string, handler func(ResponseWriter, *Request))
```

But that would be significantly different.

I have a question. Have you considered using the directives comment form for this? Such comments are distinguishable from normal human comments because they don't have a space between the `//` and the first character, and they usually have the form `//tool:subtool`, for example:

```Go
//go:generate foo bar
```

Similarly, you could use the following syntax for your "For SGo:" doc comments:

```Go
//sgo:for func(string, func(w http.ResponseWriter, req *http.Request)
func HandleFunc(pattern string, handler func(ResponseWriter, *Request))
```

Or something like that (I would imagine it'd begin with `//sgo:` but not sure as to what to place after the colon).

What do you think?

**Comment by tcard** [comment]
I'm not sure right now how would that interact with godoc and friends. Would that directive still be considered a doc comment?

"For SGo" annotations are intentionally supposed to be human-readable. One of the key principles of SGo is to keep friction with pure Go as minimal as possible. Having Go code cluttered with SGo directives works against this. If the SGo-related metadata is presented as human readable documentation, that also shows up in godoc (and godoc.org) and specifies the "contract" of the documented thing for human Go coders, this friction is reduced, in my opinion. I see your point, but I'm not sure that's the right tradeoff here.

Consider also that most of the time those comments will appear in .go files translated from adjacent .sgo files, so only people totally unacquainted with the codebase and build process could be tempted to alter them.

**Comment by shurcooL** [comment]
I see your points, and those are good arguments for keeping it more human readable.

The comments would still appear in godoc, since they're attached to the identifier. But they certainly look more "for the machine" than for humans.

I guess the challenge here is you want something that works both for humans, and for machines, but different from regular "for humans-only" comments.

When perusing Go code in general, when I see comments that look like for humans, I expect that changing them should not break the program.

I suppose my only suggestion is to try it out, and see how it looks. If the `//sgo:for` looks very ugly, then too bad. But if it grows on you and you start to find it readable/nice while still being clear that it's semantically important and not something just for humans that can be changed without breaking programs, then that's a huge win.

**Comment by tcard** [comment]
A few months have passed and I'm not aware of anybody else using or reading SGo besides me and by extension some of my coworkers that can give their input on this (if anybody else is using it, I'd love to know!). We haven't had any problem with the current form, and I still prefer it for the reasons above.

I'm closing this issue then. Thanks @shurcooL though!

**Comment by shurcooL** [comment]
Sounds good, thanks for considering it! 👍
