### ISSUE TITLE
Consider an operator for "swearing" that something is not nil.

### ISSUE THREAD

**Issue by tcard** [tcard/sgo#27]
``` go
m := map[string]map[string]int{"foo": map[string]int{}}
m["foo"]["bar"] = 123
```

This compiles in Go, but doesn't in SGo. As SGo doesn't know that `m["foo"]` is not nil, it doesn't allow you to write this without explicitly checking it.

``` go
m := map[string]?map[string]int{"foo": map[string]int{}}
mfoo := m["foo"]
if mfoo != nil {
    mfoo["bar"] = 123
}
```

This, however, can be annoying and non-idiomatic if you as a programmer know that `m["foo"]` is not nil. You can just "swear" to SGo that a value with optional type is not nil. 

Borrowing syntax from Swift:

``` go
m := map[string]?map[string]int{"foo": map[string]int{}}
mfoo := m["foo"]! // mfoo has type map[string]int and is usable right away
mfoo["bar"] = 123 // Would panic _here_ if mfoo were nil.

// Equivalently:

m["foo"]!["bar"] = 123
```

We could extend this to reads from maps, channels, etc.

``` go
m := map[string]map[string]int{"foo": map[string]int{}}
// m["foo"] needs a x \ ok = assignment, but you could bypass that:
m["foo"]!["bar"] = 123
```

See #25 for related rationale.

**Comment by shurcooL** [comment]
As a high level observation, this change would push SGo a little in the direction of Go, is that right?

Or at least it makes it possible to do that in some cases when desirable (whereas Go makes you do this _all_ the time).

**Comment by tcard** [comment]
That's right. It's pretty much a "do as Go would do here" operator.

I didn't include something like this from the beginning because 1. I wasn't sure if `!` should generate a nil-check-or-panic, à la Swift or Rust, thus keeping type safety sound, or just carry on and assume it's not nil, thus weakening SGo guarantees; and 2. I thought it wouldn't be such a big deal, as most of the time you would work with "pure" SGo types and only in corner cases you would be forced to nil-check things you know aren't nil just to use them.

I now lean towards thinking that losing some type safety by _explicitly_ falling back to Go's type safety isn't that big of a deal, and we do that anyway all the time when using reflection or importing SGo-annotated Go packages. 2 has proven to be a false assumption: depending on the program, you can end up unnecessarily nil-checking tons of stuff just to keep SGo happy, especially since SGo isn't too smart about deducing the scope in which a nil-check proves something non-nil. (One could argue, though, that such programs could be written directly in Go then.)

We could even provide both the sound and unsound versions with a flag.

**Comment by Gurpartap** [comment]
They call these, "implicitly unwrapped optionals" in Swift (with a !). The programmer has to make sure the variable is assigned a value before accessing it. Otherwise there's a crash.

**Comment by tcard** [comment]
@Gurpatap It's more like _explicitly_ unwrapped optionals. Implicitly unwrapped optionals are part of the optional's type, if I'm not mistaken: you can do `var x T!; x` and it's like doing the explicit version `var x T?; x!`. I'm proposing something like the latter, except Swift checks as soon as an optional is unwrapped that it's not nil (and crashes if it is) while I propose that we just _assume_ it's not nil, which may cause a crash later.

**Comment by Gurpartap** [comment]
In Swift, `var x: T!` actually _assumes_ that `x` will not be nil and may cause a runtime crash if used without setting a value. It compiles to `var x: ImplicitlyUnwrappedOptional<T>`. Like, "I swear it will not be nil when needed.

Whereas in `var x: T?` (or `var x: Optional<T>`), `x!` is like, "I swear it's not nil right now". `x.unwrapOrCrash(iSwear: ✌️)`

We might both be correct but on different pages [terminologically](https://gist.github.com/Gurpartap/bc72e18335fb037fcce1417793b9211e).. Please correct me if I'm wrong.

Your observation with needing to unwrap unnecessarily stands correct. Relative to example in first post, when you subscript on a dictionary, even in Swift the value is automatically assumed optional, and it lets you "swear" that it's not nil:

```swift
// We haven't set anything optional here.
let m = Dictionary<String, Dictionary<String, Int>>()

// This doesn't compile:
// m["foo"]["bar"] = 123

// Compiles (and won't crash if m["foo"] isn't set, and won't set the value either).
m["foo"]?["bar"] = 123

// Compiles (and will crash if m["foo"] isn't set).
m["foo"]!["bar"] = 123
```

While at it, perhaps might also be worth implementing the `?` operator to keep SGo's guarantees.

**Comment by tcard** [comment]
The force-unwrap branch has been merged into master, so this is into SGo now.
